name:                refluxive
version:             0.1.0.0
github:              myuon/refluxive
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           2018 myuon

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- Strict
- MultiWayIf
- TypeFamilies
- DataKinds
- PolyKinds
- FlexibleInstances
- FlexibleContexts
- LambdaCase
- TemplateHaskell
- MultiParamTypeClasses
- TypeApplications
- OverloadedLabels
- TypeOperators
- OverloadedStrings

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/myuon/refluxive#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- sdl2-ttf
- sdl2-gfx
- linear
- mtl
- extensible
- lens
- vector
- containers
- text
- mwc-random

library:
  source-dirs: src

executables:
  example-helloworld:
    main:                HelloWorld.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is HelloWorld
    dependencies:
    - refluxive
  example-todomvc:
    main:                TodoMVC.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is TodoMVC
    dependencies:
    - refluxive
  example-clickcounter:
    main:                ClickCounterButton.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is ClickCounterButton
    dependencies:
    - refluxive
  example-game-of-life:
    main:                GameOfLife.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is GameOfLife
    dependencies:
    - refluxive


